### ISSUE TITLE
Sometime \n (newline) doesn't get parsed.

### ISSUE THREAD

**Issue by itaquito** [2LSpigot/BungeeMOTD#10]
Hello!

Sometimes the \n doesn't get parsed and it appears on the MOTD, this only happens sometimes when you ping the server, other times the MOTD appears correctly.
Here is a screenshot on how it looks:
![image](https://user-images.githubusercontent.com/30180886/105406804-8a927780-5bf2-11eb-8d77-b470154324ac.png)

And how it should look like:
![image](https://user-images.githubusercontent.com/30180886/105406825-92521c00-5bf2-11eb-83de-8b8685b64d41.png)

I'm using CleanMotD on Bungee.
Version of Bungeecord (Waterfall): This server is running Waterfall version git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:40370a3:388 by md_5
Version of CleanMotD: 0.2.5

Thanks.

**Comment by linsaftw** [comment]
Of course, motd cant take multiple new lines. It can only take 2 lines. If you exceed the first it will automatically create the new one and not take the \n. Can't really fix this.
