### ISSUE TITLE
Can't put the first motd line in the middle

### ISSUE THREAD

**Issue by TheDesignCraftYT** [2LSpigot/BungeeMOTD#15]
Hey!
I'm trying to put the first line of my motd to the middle but its not working.
With the second line, its working.
![grafik](https://user-images.githubusercontent.com/84375152/158184939-947b9ab8-946c-4449-a7a3-a0120c6c4347.png)
![grafik](https://user-images.githubusercontent.com/84375152/158184992-30486083-88e5-4cd7-bb40-dd0334641c80.png)

**Comment by linsaftw** [comment]
Write a &r at the start of the line. (&r      &bYour text) This is due to yml reading and cannot be fixed from CleanMotd.
