### ISSUE TITLE
Velocity Support

### ISSUE THREAD

**Issue by Thin-Troll** [2LSpigot/BungeeMOTD#16]
Velocity is a Minecraft: Java Edition Proxy - more information about it at https://velocitypowered.com/

I believe that ChatSentinel having Velocity support would be really great as Velocity has been growing really quickly recently and having more great plugins such as CleanMOTD natively available on Velocity would be really good!

**Comment by linsaftw** [comment]
For motd it would be better that velocity improves their own motd system for better performance.

**Comment by 4drian3d** [comment]
Implemented in #18
