### ISSUE TITLE
HEX support

### ISSUE THREAD

**Issue by JHarris12345** [2LSpigot/BungeeMOTD#19]
Since a lot of plugins allow the use of HEX codes in bungee, I think this plugin should allow it too

**Comment by JHarris12345** [comment]
I believe flamecord is the one preventing it working. People are able to get it to work using this format: &x&F&B&F&5&B&D

And when I output my MOTD, it looks like it translated the hex fine. But the player is not receiving it translated properly
![image](https://user-images.githubusercontent.com/46936647/189494382-778ba48f-749e-4b60-a34a-f54b959a9883.png)

**Comment by linsaftw** [comment]
Does it work fine with BungeeCord/Waterfall?

**Comment by xism4** [comment]
> And when I output my MOTD, it looks like it translated the hex fine. But the player is not receiving it translated properly

Migth the plugin should use ComponentBuilder instead a text component.

**Comment by linsaftw** [comment]
Terrible idea to actually use HEX ni motds as it makes the server vulnerable to DDoS attacks.
