### ISSUE TITLE
Request: Add Profiles

### ISSUE THREAD

**Issue by JasonHorkles** [2LSpigot/BungeeMOTD#2]
It'd be nice if there could be profiles you can load so the motd will change on-demand. Would this be a possibility?

**Comment by linsaftw** [comment]
You can always reload the plugin with /cleanmotd reload :)

**Comment by JasonHorkles** [comment]
Well yeah but it'd just be useful if I could do something like `/cleanmotd profile <profile>` so I can switch back and forth easily

If it's not gonna be a thing I probably won't bother switching plugins, thanks anyways

**Comment by linsaftw** [comment]
I will see what i can do about it, but i want to keep cleanmotd as clean as possible :)
