### ISSUE TITLE
1.16 hex color support

### ISSUE THREAD

**Issue by AfkF24** [2LSpigot/BungeeMOTD#3]
Could we get Minecraft's 1.16 hex color support? Seems like a great idea, especially for a MOTD plugin.
Also having some extra color manipulation through rainbow and gradient colors for example sounds quite cool too.

Cheers

**Comment by linsaftw** [comment]
Hi, can you explain how to implement this? I've read some forums and it says that by using ChatColor.replaceAlternateColorCodes(...) it will work.

**Comment by AfkF24** [comment]
Afaik, rgb and hex colors can be used through BungeeCord's ChatColor, so `ChatColor#of(Color)` and `ChatColor#of(String)`. Haven't really messed around with hex colors at all, just saw some servers use them in MOTD's with fancy gradients and stuff.

**Comment by linsaftw** [comment]
Ok i will use the official ChatColor methods and see if that works for hexing.

**Comment by linsaftw** [comment]
[CleanMotD.zip](https://github.com/2LStudios-MC/CleanMotD/files/5405476/CleanMotD.zip)

Hi, please check if its fixed with this version. Re-open the issue if you still have problems.
