### ISSUE TITLE
No escape character for '&'

### ISSUE THREAD

**Issue by kaxonomy** [2LSpigot/BungeeMOTD#6]
Motds have limited space and new server features are easier to list when you can use the '&' unicode in plaintext. Currently all &'s format to a color code regardless if formatted as \u0026. Using a forward slash ` \ ` before the character would be an easy way to escape and follow similar format escaping conventions such as Discord.

This issue has been tested on the bungeecord version.

**Comment by linsaftw** [comment]
Hi, this is handled by your Bungee/Spigot ChatColor.translateAlternateColorCodes()
