### ISSUE TITLE
Protocol changing option is broken (Bungee)

### ISSUE THREAD

**Issue by AfkF24** [2LSpigot/BungeeMOTD#9]
Basically the title. Brand name is `unknown` on various server pinging sites, and loading a newer version than supported doesn't display any brand/protocol name. https://prnt.sc/we571h

**Comment by linsaftw** [comment]
This is handled by ProtocolLib in Spigot and handled by BungeeCord in BungeeCord there is nothing we can do about this. (From what i know)
